language: objective-c
cache: cocoapods
rvm: 2.2.2
osx_image: xcode11
before_install:
  - brew update

  # Only if app has Carthage dependencies
  - carthage bootstrap --verbose

script:
  - carthage build --no-skip-current
  - |
    xcodebuild test \
    -project LexisDatabase.xcodeproj \
    -scheme LexisDatabase \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
